accounts/urls.py
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from django.conf import settings

from . import views
from .views import register_magistrate, ResetPasswordView, PasswordResetConfirmationView


app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('accounts:login')), name='logout'),
    path('register/', views.register, name='register'),
    path('register-magistrate/', register_magistrate, name='register_magistrate'),
    path('update/<int:pk>/', views.UserUpdateView.as_view(), name='user_update'),
    path('list/', views.UserListView.as_view(), name='user_list'),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmationView.as_view(), name='password_reset_confirmation'),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('request_deletion/<int:pk>/', views.request_deletion, name='request_deletion'),
    path('cancel_deletion/<int:pk>/', views.cancel_deletion, name='cancel_deletion'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fExtra/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.i18n import set_language
from django.conf import settings
from fExtra import views
from fExtra.views import privacy_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('Payments/', include('Payments.urls', namespace='Payments')),

    path('privacy/', privacy_view, name='privacy'),
    re_path(r'^i18n/setlang/$', set_language, name='set_language'),
    path('', views.home, name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import BaseUserManager, PermissionsMixin, AbstractUser
from django.db import models
from django.utils import timezone
from guardian.shortcuts import assign_perm
from datetime import timedelta

from .validations import validate_image


class CustomUserManager(BaseUserManager):
    def create_user(self, email, role="parent", password=None, **extra_fields):
        if not email:
            raise ValueError('Users must have an email address')

        email = self.normalize_email(email)
        user = self.model(email=email, role=role, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        if role == 'parent':
            assign_perm('accounts.view_user', user, user)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('role', 'administrator')
        return self.create_user(email, password=password, **extra_fields)


class User(AbstractUser, PermissionsMixin):
    ROLE_CHOICES = [
        ('administrator', 'Administrator'),
        ('lawyer', 'Attorney'),
        ('judge', 'Judge'),
        ('parent', 'Parent'),
    ]
    username = models.CharField(max_length=150, unique=False, null=True, blank=True)
    email = models.EmailField(verbose_name='e-mail address', unique=True, max_length=255)
    is_active = models.BooleanField(default=True)
    deletion_requested_at = models.DateTimeField(null=True, blank=True)
    role = models.CharField(max_length=13, choices=ROLE_CHOICES, default='parent')
    is_staff = models.BooleanField(default=False)
    gender = models.CharField(max_length=1, choices=[('M', 'Male'), ('F', 'Female'), ('X', 'They')], null=True, blank=True, default=' ')
    last_name = models.CharField('last name', max_length=150, blank=True)
    first_name = models.CharField('first name', max_length=30, blank=True)
    date_of_birth = models.DateField(default=timezone.now)
    telephone = models.CharField(max_length=16, null=True, blank=True)
    address = models.CharField(null=True, blank=True, max_length=75)
    national_number_raw = models.CharField(max_length=11, blank=True, null=True)
    national_number = models.CharField(max_length=15, blank=True, null=True)
    profile_image = models.ImageField(upload_to='profile_images/', default='profile_images/default.jpg', validators=[validate_image])

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']
    objects = CustomUserManager()

    def __str__(self):
        return f"{self.last_name} {self.first_name} ({self.email})"

    @property
    def is_administrator(self):
        return self.role == 'administrator'

    def is_lawyer(self):
        return self.role == 'lawyer'

    def is_judge(self):
        return self.role == 'judge'

    @property
    def is_parent(self):
        return self.role == 'parent'

    def request_deletion(self):
        self.deletion_requested_at = timezone.now()
        self.save()

    def cancel_deletion(self):
        self.deletion_requested_at = None
        self.save()

    def is_deletion_pending(self):
        return self.deletion_requested_at and (timezone.now() < self.deletion_requested_at + timedelta(days=30))


class AvocatParent(models.Model):
    avocat = models.ForeignKey(User, related_name='assigned_parents', on_delete=models.CASCADE)
    parent = models.ForeignKey(User, related_name='avocats_assigned', on_delete=models.CASCADE)

    class Meta:
        unique_together = (('avocat', 'parent'),)

    def __str__(self):
        return f"{self.avocat.email} assigned to {self.parent.email}"


class JugeParent(models.Model):
    juge = models.ForeignKey(User, related_name='assigned_parents_judge', on_delete=models.CASCADE)
    parent = models.ForeignKey(User, related_name='juges_assigned', on_delete=models.CASCADE)

    class Meta:
        unique_together = (('juge', 'parent'),)

    def __str__(self):
        return f"{self.juge.email} assigned to {self.parent.email}"

accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, get_user_model
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q, Count
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic import ListView, UpdateView
from pip._internal.utils import logging

from .forms import MagistrateRegistrationForm, UserRegisterForm, UserUpdateForm, CancelDeletionForm, DeletionRequestForm
from .models import User, AvocatParent, JugeParent

User = get_user_model()

logger = logging.getLogger(__name__)

class UserListView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'accounts/user_list.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return HttpResponseRedirect(reverse('home'))
        return super().dispatch(request, *args, **kwargs)

    def get_active_status_filter(self):
        is_active_str = self.request.GET.get('is_active')
        if is_active_str is not None:
            return is_active_str.lower() in ['true', '1', 't']
        return None

    def render_to_response(self, context, **response_kwargs):
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            try:
                magistrates_list = [{
                    'id': mag.id,
                    'profile_image_url': self.get_image_url(mag),
                    'first_name': mag.first_name,
                    'last_name': mag.last_name,
                    'email': mag.email,
                    'role': mag.role,
                    'parents_count': mag.assigned_parents.count() + mag.assigned_parents_judge.count()
                } for mag in context['magistrates']]

                parents_list = [{
                    'id': parent.id,
                    'profile_image_url': self.get_image_url(parent),
                    'first_name': parent.first_name,
                    'last_name': parent.last_name,
                    'email': parent.email,
                    'avocats_assigned': [
                        avocat.avocat.last_name for avocat in parent.avocats_assigned.all()
                        if avocat.avocat.is_active or not parent.is_active
                    ],
                    'juges_assigned': [
                        juge.juge.last_name for juge in parent.juges_assigned.all()
                        if juge.juge.is_active or not parent.is_active
                    ]
                } for parent in context['parents_filtered']]

                return JsonResponse({'magistrates': magistrates_list, 'parents': parents_list})
            except Exception as e:
                logger.error(f"Error in AJAX response: {e}")
                return JsonResponse({'error': str(e)}, status=500)
        else:
            return super().render_to_response(context, **response_kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        is_active = self.get_active_status_filter()

        try:
            magistrates_query = User.objects.filter(
                Q(is_staff=True) | Q(is_superuser=True) | Q(role='administrator') | Q(role='lawyer') | Q(role='judge')
            )
            parents_query = User.objects.filter(role='parent').prefetch_related('avocats_assigned__avocat', 'juges_assigned__juge')

            if is_active is not None:
                magistrates_query = magistrates_query.filter(is_active=is_active)
                parents_query = parents_query.filter(is_active=is_active)

            context['magistrates'] = magistrates_query.annotate(parents_count=Count('assigned_parents') + Count('assigned_parents_judge'))

            if self.request.user.role == 'lawyer':
                context['parents_filtered'] = parents_query.filter(avocats_assigned__avocat=self.request.user).distinct()
            elif self.request.user.role == 'judge':
                context['parents_filtered'] = parents_query.filter(juges_assigned__juge=self.request.user).distinct()
            else:
                context['parents_filtered'] = parents_query

        except Exception as e:
            logger.error(f"Error in context data: {e}")
            context['magistrates'] = []
            context['parents_filtered'] = []

        return context

    def get_image_url(self, user):
        if user.profile_image and hasattr(user.profile_image, 'url'):
            return self.request.build_absolute_uri(user.profile_image.url)
        else:
            return self.request.build_absolute_uri(settings.MEDIA_URL + 'profile_images/default.jpg')


class UserUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = get_user_model()
    template_name = 'accounts/user_update.html'
    form_class = UserUpdateForm
    success_url = reverse_lazy('accounts:user_list')

    def test_func(self):
        user_to_update = self.get_object()

        if self.request.user.is_superuser:
            return True
        if self.request.user.role == 'lawyer':
            return AvocatParent.objects.filter(avocat=self.request.user, parent=user_to_update).exists()
        if self.request.user.role == 'judge':
            return JugeParent.objects.filter(juge=self.request.user, parent=user_to_update).exists()
        if self.request.user == user_to_update:
            return True
        return False

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request_user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        if not self.request.user.is_superuser:
            if 'role' in form.changed_data:
                form.add_error('role', "Vous n'êtes pas autorisé à modifier le rôle.")
                return self.form_invalid(form)

        response = super().form_valid(form)
        related_users_ids = set(form.cleaned_data.get('related_users').values_list('id', flat=True))

        if self.object.role == 'lawyer':
            relationship_field = 'parent'
            own_field = 'avocat'
            relationship_model = AvocatParent
        elif self.object.role == 'judge':
            relationship_field = 'parent'
            own_field = 'juge'
            relationship_model = JugeParent
        elif self.object.role == 'parent':
            relationship_field = 'juge'
            own_field = 'parent'
            relationship_model = JugeParent
        else:
            return response

        current_relations = set(relationship_model.objects.filter(**{own_field: self.object}).values_list(
            relationship_field + '_id', flat=True))

        relationships_to_add = related_users_ids - current_relations
        relationships_to_remove = current_relations - related_users_ids

        relationship_model.objects.filter(
            **{own_field: self.object, relationship_field + '_id__in': relationships_to_remove}).delete()

        User = get_user_model()
        for user_id in relationships_to_add:
            user_instance = User.objects.get(pk=user_id)
            relationship_model.objects.get_or_create(**{
                own_field: self.object,
                relationship_field: user_instance
            })
        return response


@login_required
@permission_required('accounts.add_user', raise_exception=True)
@user_passes_test(lambda u: u.is_superuser, login_url='/login/')
def register_magistrate(request):
    if request.method == 'POST':
        form = MagistrateRegistrationForm(request.POST)
        if form.is_valid():
            magistrate = form.save()
            messages.success(request, _('Lawyer "%s" registered successfully.' % magistrate.email))
            return redirect(reverse('accounts:user_list'))
    else:
        form = MagistrateRegistrationForm()
    return render(request, 'registration/register_magistrate.html', {'form': form})


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.role = 'parent'
            user.national_number_raw = form.cleaned_data['national_number']
            formatted_number = form.cleaned_data['national_number'][:2] + '.' + form.cleaned_data['national_number'][2:4] + '.' + form.cleaned_data['national_number'][4:6] + '-' + form.cleaned_data['national_number'][6:9] + '.' + form.cleaned_data['national_number'][9:]
            user.national_number = formatted_number
            user.save()

            if not request.user.is_authenticated:
                login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                messages.success(request, _("Your account has been created! You are now logged in."))
                return redirect('home')
            else:
                if request.user.role == 'avocat':
                    AvocatParent.objects.create(avocat=request.user, parent=user)
                elif request.user.role == 'juge':
                    JugeParent.objects.create(juge=request.user, parent=user)

                messages.success(request, _("The parent account has been successfully created."))
                return redirect('/accounts/list/')
    else:
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'registration/password_reset.html'

accounts/templates/accounts/cancel_deletion.html
{% extends "fExtra/base.html" %}
{% load i18n %}
{% block content %}
    <h2>{% trans "Cancel Account Deletion" %}</h2>
    <p>{% trans "If you cancel the deletion request, your account will not be deleted. You can always request deletion again if needed." %}</p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Cancel Deletion Request" %}</button>
    </form>
    <a href="{% url 'accounts:user_update' user.pk %}">{% trans "Back to Profile" %}</a>
{% endblock %}

accounts/templates/accounts/request_deletion.html
{% extends "fExtra/base.html" %}
{% load i18n %}
{% block content %}
    <h2>{% trans "Request Account Deletion" %}</h2>
    <p>{% trans "Once you request account deletion, your account will be scheduled for deletion after 30 days. During this period, you can cancel the deletion request at any time. Please note that the webmaster might delete your account before the 30 days period ends." %}</p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Request Deletion" %}</button>
    </form>
{% endblock %}

accounts/templates/accounts/user_list.html
{% extends 'fExtra/base.html' %}
{% load static i18n %}

{% block content %}

    <link rel="stylesheet" href="{% static 'accounts/css/user_list.css' %}">

    <!--  Filters  -->
    <div class="filter-section mb-3">
        <div class="form-check form-switch">
            <input class="form-check-input" type="checkbox" id="isActiveFilter" checked>
            <label class="form-check-label" for="isActiveFilter">{% trans "Active" %}</label>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card mb-4">
                    <div class="card-body">
                        <h2 class="card-title">{% trans "Attorneys - Lawyers - Judges" %}</h2>
                        <table class="table">
                            <thead>
                            <tr>
                                <th></th>
                                <th>{% trans "Last Name" %}</th>
                                <th>{% trans "First Name" %}</th>
                                <th>{% trans "Email" %}</th>
                                <th>{% trans "Role" %}</th>
                                <th>{% trans "Case" %}</th>
                            </tr>
                            </thead>
                            <tbody class="magistrates-list">
                            {% for magistrate in magistrates %}
                                <tr class="magistrate-item" data-user-id="{{ magistrate.id }}">
                                    <td><img src="{{ magistrate.profile_image_url }}" alt="{{ magistrate.first_name }} {{ magistrate.last_name }}" width="30" height="30" class="rounded-circle"></td>
                                    <td>{{ magistrate.last_name }}</td>
                                    <td>{{ magistrate.first_name }}</td>
                                    <td>{{ magistrate.email }}</td>
                                    <td>
                                        {% if magistrate.is_superuser %}Administrator
                                        {% elif magistrate.role == 'admin' %}Administrator
                                        {% elif magistrate.role == 'lawyer' %}Lawyer
                                        {% elif magistrate.role == 'judge' %}Judge
                                        {% else %}Parent
                                        {% endif %}
                                    </td>
                                    <td>{{ magistrate.parents_count }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="card mb-4">
                    <div class="card-body">
                        <h2 class="card-title">{% trans "Parents List" %}</h2>
                        <!-- Parents table -->
                        <table class="table">
                            <thead>
                            <tr>
                                <th></th>
                                <th>{% trans "Last Name" %}</th>
                                <th>{% trans "First Name" %}</th>
                                <th>{% trans "Email" %}</th>
                                <th>{% trans "Referent" %}</th>
                            </tr>
                            </thead>
                            <tbody class="parents-list">
                            {% for parent in parents %}
                                <tr class="parent-item" data-user-id="{{ parent.id }}">
                                    <td><img src="{{ parent.profile_image_url }}" alt="{% trans 'Profile Image' %}" width="30" height="30" class="rounded-circle"></td>
                                    <td>{{ parent.last_name }}</td>
                                    <td>{{ parent.first_name }}</td>
                                    <td>{{ parent.email }}</td>
                                    <td>
                                        {% for avocat in parent.avocats_assigned %}
                                            {{ avocat.avocat.last_name }}<br>
                                        {% endfor %}
                                        {% for juge in parent.juges_assigned %}
                                            {{ juge.juge.last_name }}<br>
                                        {% endfor %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'accounts/js/user_list.js' %}"></script>

{% endblock %}

accounts/templates/accounts/user_update.html
{% extends 'fExtra/base.html' %}
{% load static i18n crispy_forms_tags %}

{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card shadow-sm">
                    <div class="card-header bg-primary text-white">
                        <h3 class="text-center mb-0">
                            {% trans "Profile" %}: {% trans user.role %}
                        </h3>
                    </div>
                    <div class="card-body">
                        <div class="d-flex align-items-center mb-3">
                            <img src="{{ user.profile_image.url }}" alt="{% trans "Profile image" %}" width="100" height="100" class="rounded-circle me-3">
                            <div>
                                {% if user.is_deletion_pending %}
                                    <p>{% trans "Your account is scheduled for deletion on" %} {{ user.deletion_requested_at|date:"Y-m-d" }}.</p>
                                    <a href="{% url 'accounts:cancel_deletion' user.pk %}">{% trans "Cancel Deletion Request" %}</a>
                                {% else %}
                                    <a href="{% url 'accounts:request_deletion' user.pk %}">{% trans "Request Account Deletion" %}</a>
                                {% endif %}

                            {% if request.user.is_superuser %}
                                {% if user.is_deletion_pending %}
                                    <p>{% trans "User has requested account deletion." %}</p>
{#TODO: pictogramme poubelle pour supprimer toutes les données par un superuser#}
{#                                    <img src="{% static 'images/red_bin.png' %}" alt="{% trans "Delete Requested" %}">#}
                                {% endif %}
                            {% endif %}

                                <h4>{{ user.last_name }} {{ user.first_name }}</h4>
                                <!-- switch is_active -->
                                {% if form.fields.is_active %}
                                    <div class="form-check form-switch">
                                        <input class="form-check-input" type="checkbox" id="isActiveSwitch" name="is_active_toggle" {% if user.is_active %}checked{% endif %}>
                                        <label class="form-check-label" for="isActiveSwitch">{% trans "Active" %}</label>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% for field in form.visible_fields %}
                                {% if field.name != 'is_active' %}
                                    <div class="mb-3">
                                        {{ field|as_crispy_field }}
                                    </div>
                                {% endif %}
                            {% endfor %}
                            <button type="submit" class="btn btn-outline-primary">{% trans "Save changes" %}</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}