Payments/urls.py
from django.conf.urls.static import static
from django.urls import path
from django.conf import settings

from . import views
from .views import PaymentHistoryView, MagistrateFolderListView, FolderPaymentHistoryView, \
    submit_payment_document_lawyer, PaymentDeleteView, CategoryPaymentsView, add_category

app_name = 'Payments'
urlpatterns = [
    path('parent-add-payment/', views.submit_payment_document, name='parent-add-payment'),
    path('add_category/', add_category, name='add_category'),
    path('parent-payment-history/', PaymentHistoryView.as_view(), name='parent-payment-history'),
    path('parent-payment-history/category/<int:category_id>/', CategoryPaymentsView.as_view(), name='category-payments'),
    path('create_folder/', views.create_folder, name='create_folder'),
    path('list_folder/', MagistrateFolderListView.as_view(), name='list_folder'),
    path('magistrate-/<int:folder_id>/', FolderPaymentHistoryView.as_view(), name='magistrate_folder_payment_history'),
    path('lawyer-add-payment/<int:folder_id>/', submit_payment_document_lawyer, name='lawyer-add-payment'),
    path('delete-payment/<int:pk>/', PaymentDeleteView.as_view(), name='delete_payment'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fExtra/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.i18n import set_language
from django.conf import settings
from fExtra import views
from fExtra.views import privacy_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('Payments/', include('Payments.urls', namespace='Payments')),

    path('privacy/', privacy_view, name='privacy'),
    re_path(r'^i18n/setlang/$', set_language, name='set_language'),
    path('', views.home, name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Payments/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone


class CategoryType(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class PaymentCategory(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    type = models.ForeignKey(CategoryType, on_delete=models.CASCADE, related_name='payment_categories')

    def __str__(self):
        return self.name


class PaymentDocument(models.Model):
    STATUS_CHOICES = (
        ('pending', 'Pending'),  # En attente de validation
        ('validated', 'Validated'),  # Validé par l'avocat
        ('rejected', 'Rejected'),  # Rejeté par l'avocat
    )
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    folder = models.ForeignKey('Folder', on_delete=models.CASCADE, related_name='payment_documents', blank=True, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField(default=timezone.now)
    category = models.ForeignKey(PaymentCategory, on_delete=models.CASCADE, related_name='payments', blank=False)
    document = models.FileField(upload_to='payment_documents/', blank=True, null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')

    def __str__(self):
        return f"Payment Document - {self.user.username} - {self.date} - {self.amount}"

    def user_can_delete(self, user):
        return self.user == user

    def is_validated(self):
        return self.status == 'validated'


class Folder(models.Model):
    lawyer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='folders_in_charge')
    judge = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='folders_visible', null=True, blank=True)
    parent1 = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='folders_as_parent1')
    parent2 = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='folders_as_parent2')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Folder managed by {self.lawyer} with parents {self.parent1} and {self.parent2}"

Payments/forms.py
from django import forms

from accounts.views import User
from .models import PaymentDocument, Folder, PaymentCategory


class PaymentDocumentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].queryset = PaymentCategory.objects.order_by('type', 'name')
        self.fields['category'].required = True

    class Meta:
        model = PaymentDocument
        fields = ['amount', 'category', 'date', 'document']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'})
        }


class PaymentDocumentFormLawyer(forms.ModelForm):
    parent = forms.ChoiceField(choices=())

    class Meta:
        model = PaymentDocument
        fields = ['amount', 'category', 'date', 'document', 'parent']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'})
        }

    def __init__(self, *args, **kwargs):
        parent_choices = kwargs.pop('parent_choices', None)
        super().__init__(*args, **kwargs)
        if parent_choices:
            self.fields['parent'].choices = parent_choices


class FolderForm(forms.ModelForm):
    class Meta:
        model = Folder
        fields = ['judge', 'parent1', 'parent2']

    def __init__(self, *args, **kwargs):
        super(FolderForm, self).__init__(*args, **kwargs)
        self.fields['judge'].queryset = User.objects.filter(role='judge')
        self.fields['parent1'].queryset = User.objects.filter(role='parent')
        self.fields['parent2'].queryset = User.objects.filter(role='parent')

Payments/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.db.models import Sum, Q
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.utils.text import capfirst
from django.views.decorators.http import require_POST
from django.views.generic import ListView, DeleteView

from .forms import PaymentDocumentForm, FolderForm, PaymentDocumentFormLawyer
from .models import PaymentDocument, Folder, PaymentCategory, CategoryType

User = get_user_model()


# View for parent
class PaymentHistoryView(LoginRequiredMixin, ListView):
    model = PaymentDocument
    template_name = 'Payments/parent_payment_history.html'
    context_object_name = 'payments'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        user = self.request.user
        self.folder = get_object_or_404(Folder, Q(parent1=user) | Q(parent2=user))
        return PaymentDocument.objects.filter(folder=self.folder)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        folder = self.folder
        other_parent = folder.parent1 if user == folder.parent2 else folder.parent2

        # Retrieve only validated payments for both parents and group by category type
        parent1_valid_payments = PaymentDocument.objects.filter(user=folder.parent1, category__type__isnull=False,
                                                                status='validated').values(
            'category__type', 'category').annotate(total_amount=Sum('amount'))
        parent2_valid_payments = PaymentDocument.objects.filter(user=folder.parent2, category__type__isnull=False,
                                                                status='validated').values(
            'category__type', 'category').annotate(total_amount=Sum('amount'))

        # Retrieve pending payments for both parents
        parent1_pending_payments = PaymentDocument.objects.filter(user=folder.parent1, category__type__isnull=False,
                                                                  status='pending').values(
            'category__type', 'category').annotate(total_amount=Sum('amount'))
        parent2_pending_payments = PaymentDocument.objects.filter(user=folder.parent2, category__type__isnull=False,
                                                                  status='pending').values(
            'category__type', 'category').annotate(total_amount=Sum('amount'))

        # Create dictionaries to store payments by category type
        parent1_valid_payments_dict = {(payment['category__type'], payment['category']): payment['total_amount'] for
                                       payment
                                       in parent1_valid_payments}
        parent2_valid_payments_dict = {(payment['category__type'], payment['category']): payment['total_amount'] for
                                       payment
                                       in parent2_valid_payments}

        parent1_pending_dict = {(payment['category__type'], payment['category']): payment['total_amount'] for payment
                                in parent1_pending_payments}
        parent2_pending_dict = {(payment['category__type'], payment['category']): payment['total_amount'] for payment
                                in parent2_pending_payments}

        # Get all categories with their type
        categories = PaymentCategory.objects.filter(type__isnull=False)

        # Ensure all category types are included
        categories_by_type = {}
        for category in categories:
            category_type_id = category.type_id
            parent1_amount = parent1_valid_payments_dict.get((category_type_id, category.id), 0)
            parent2_amount = parent2_valid_payments_dict.get((category_type_id, category.id), 0)

            parent1_pending_amount = parent1_pending_dict.get((category_type_id, category.id), 0)
            parent2_pending_amount = parent2_pending_dict.get((category_type_id, category.id), 0)

            # Exclude categories where both parents have 0 amount
            if parent1_amount == 0 and parent2_amount == 0 and parent1_pending_amount == 0 and parent2_pending_amount == 0:
                continue

            if category_type_id not in categories_by_type:
                categories_by_type[category_type_id] = {
                    'type_name': category.type.name,
                    'categories': [],
                }
            categories_by_type[category_type_id]['categories'].append({
                'category_id': category.id,
                'category_name': category.name,
                'parent1_amount': parent1_amount,
                'parent2_amount': parent2_amount,
                'parent1_pending_amount': parent1_pending_amount,
                'parent2_pending_amount': parent2_pending_amount,
                'details_url': reverse('Payments:category-payments', args=[category.id])
            })

        # Calculate totals and other comparative data
        parent1_total = sum(parent1_valid_payments_dict.values())
        parent2_total = sum(parent2_valid_payments_dict.values())
        difference = abs(parent1_total - parent2_total)
        in_favor_of = folder.parent1 if parent1_total > parent2_total else folder.parent2

        context.update({
            'parent1_user': folder.parent1,
            'parent2_user': folder.parent2,
            'categories_by_type': categories_by_type,
            'parent1_total': parent1_total,
            'parent2_total': parent2_total,
            'total_amount': parent1_total + parent2_total,
            'difference': difference,
            'in_favor_of': in_favor_of,
            'other_parent_name': f"{other_parent.first_name} {other_parent.last_name}",
            'other_parent_total': parent2_total if user == folder.parent1 else parent1_total,
            'your_total': parent1_total if user == folder.parent1 else parent2_total,
        })

        # Pass user_can_delete for each payment
        payments_with_permissions = [
            {
                'payment': payment,
                'can_delete': payment.user_can_delete(user)
            } for payment in self.get_queryset()
        ]
        context['payments_with_permissions'] = payments_with_permissions

        return context


class CategoryPaymentsView(LoginRequiredMixin, ListView):
    model = PaymentDocument
    template_name = 'Payments/parent_category_history.html'
    context_object_name = 'payments'

    def get_queryset(self):
        category_id = self.kwargs['category_id']
        folder = get_object_or_404(Folder, Q(parent1=self.request.user) | Q(parent2=self.request.user))
        return PaymentDocument.objects.filter(folder=folder, category_id=category_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = get_object_or_404(PaymentCategory, id=self.kwargs['category_id'])
        context['category'] = category

        folder = get_object_or_404(Folder, Q(parent1=self.request.user) | Q(parent2=self.request.user))
        parent1_payments = PaymentDocument.objects.filter(folder=folder, category_id=self.kwargs['category_id'],
                                                          user=folder.parent1)
        parent2_payments = PaymentDocument.objects.filter(folder=folder, category_id=self.kwargs['category_id'],
                                                          user=folder.parent2)

        context['parent1_payments'] = parent1_payments
        context['parent2_payments'] = parent2_payments
        context['parent1_name'] = folder.parent1.get_full_name()
        context['parent2_name'] = folder.parent2.get_full_name()

        return context


class PaymentDeleteView(LoginRequiredMixin, DeleteView):
    model = PaymentDocument

    def get_queryset(self):
        user = self.request.user
        queryset = super().get_queryset()
        return queryset.filter(user=user)

    def get_success_url(self):
        payment_document = self.object
        return reverse('Payments:parent-payment-history')


# For judge and lawyer (only see the folders assigned to them)
class MagistrateFolderListView(LoginRequiredMixin, ListView):
    model = Folder
    template_name = 'Payments/list_folder.html'
    context_object_name = 'folders'

    def get_queryset(self):
        user = self.request.user
        # Filter cases by user logged in as judge or lawyer
        return Folder.objects.filter(Q(judge=user) | Q(lawyer=user))


# For judge and lawyer (see all payments of one folder)
class FolderPaymentHistoryView(LoginRequiredMixin, ListView):
    model = PaymentDocument
    template_name = 'Payments/magistrate_folder_payment_history.html'
    context_object_name = 'payments'

    def get_queryset(self):
        folder = get_object_or_404(Folder, pk=self.kwargs['folder_id'])
        return PaymentDocument.objects.filter(user__in=[folder.parent1, folder.parent2])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        folder = get_object_or_404(Folder, pk=self.kwargs['folder_id'])
        context['folder'] = folder
        # Calculate the total amount for parent1 and parent2 separately
        parent1_total = PaymentDocument.objects.filter(user=folder.parent1).aggregate(total_amount=Sum('amount'))['total_amount'] or 0
        parent2_total = PaymentDocument.objects.filter(user=folder.parent2).aggregate(total_amount=Sum('amount'))['total_amount'] or 0
        context['parent1_total'] = parent1_total

Payments/templates/Payments/history.html
{% extends 'fExtra/base.html' %}
{% load static i18n %}

{% block content %}
<link rel="stylesheet" href="{% static 'Payments/css/history.css' %}">

<div class="container-fluid">
    <div class="row">
        <div class="col-md-9">
            <div class="card mb-4">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <h2 class="card-title mb-0">{% trans "Payments List" %}</h2>
                        {% if request.user.role == 'lawyer' or request.user.role == 'parent' %}
                        <a href="{% url 'Payments:add-doc' %}" class="btn btn-primary">{% trans "Add Payment Document" %}</a>
                        {% endif %}
                    </div>
                    <!-- Payments table -->
                    <table class="table">
                        <thead>
                            <tr>
                                <th>{% trans "Username" %}</th>
                                <th>{% trans "Date" %}</th>
                                <th>{% trans "Amount" %}</th>
                                <th>{% trans "Document" %}</th>
                                <th>{% trans "Actions" %}</th>
                            </tr>
                        </thead>
                        <tbody class="payments-list">
                            {% for item in payments_with_permissions %}
                                <tr class="payment-item">
                                    <td>{{ item.payment.user.first_name }} {{ item.payment.user.last_name }}</td>
                                    <td>{{ item.payment.date }}</td>
                                    <td>{{ item.payment.amount }}</td>
                                    <td>
                                        {% if item.payment.document %}
                                            <div class="document-preview">
                                                <a href="{{ item.payment.document.url }}" class="btn btn-warning" target="_blank" title='{% trans "Document Preview" %}'>
                                                    {% trans "View" %}
                                                </a>
                                                <div class="tooltip">
                                                    <img src="{{ item.payment.document.url }}" alt='{% trans "Document Preview" %}' style="width: 100px;">
                                                </div>
                                            </div>
                                        {% else %}
                                            {% trans "No Document" %}
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if item.can_delete %}
                                            <form action="{% url 'Payments:delete_payment' item.payment.pk %}" method="post" style="display:inline;">
                                                {% csrf_token %}
                                                <button type="submit" class="btn btn-danger" title="{% trans 'Delete' %}">
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                            </form>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card mb-4">
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>{% trans "Total Amount" %}</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>{% trans "Your Total" %}: {{ your_total }} €</td>
                            </tr>
                            <tr>
                                <td>{{ other_parent_name }} {% trans "Total" %}: {{ other_parent_total }} €</td>
                            </tr>
                            <tr>
                                <td>{{ difference }} € {% trans "In Favor Of" %} {{ in_favor_of.first_name }} {{ in_favor_of.last_name }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Payments/templates/Payments/list_folder.html
{% extends 'fExtra/base.html' %}
{% load i18n %}

{% block title %}{% trans "My Folders" %}{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>{% trans "My Folders" %}</h2>
    {% if folders %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>{% trans "Parent 1" %}</th>
                <th>{% trans "Parent 2" %}</th>
                <th>{% trans "Created at" %}</th>
                <th>{% trans "Actions" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for folder in folders %}
            <tr>
                <td>{{ folder.parent1.first_name }} {{ folder.parent1.last_name }}</td>
                <td>{{ folder.parent2.first_name }} {{ folder.parent2.last_name }}</td>
                <td>{{ folder.created_at }}</td>
                <td>
                    <a href="{% url 'Payments:magistrate_folder_payment_history' folder.id %}" class="btn btn-info">
                        {% trans "View Payment History" %}
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <p>{% trans "You have no folders." %}</p>
    {% endif %}
</div>
{% endblock %}

Payments/templates/Payments/magistrate_folder_payment_history.html
{% extends 'fExtra/base.html' %}
{% load static i18n %}

{% block content %}

<link rel="stylesheet" href="{% static 'Payments/css/history.css' %}">

<div class="container-fluid">
    <div class="row">
        <div class="col-md-9">
            <div class="card mb-4">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <h2 class="card-title mb-0">{% trans "Payments List" %}</h2>
                        {% if request.user.role == 'lawyer' or request.user.role == 'parent' %}
                        <a href="{% url 'Payments:lawyer-add-payment' folder_id=folder.id %}" class="btn btn-primary">{% trans "Add Payment Document" %}</a>
                        {% endif %}
                    </div>
                    <!-- Payments table -->
                    <table class="table">
                        <thead>
                            <tr>
                                <th>{% trans "Username" %}</th>
                                <th>{% trans "Date" %}</th>
                                <th>{% trans "Amount" %}</th>
                                <th>{% trans "Document" %}</th>
                            </tr>
                        </thead>
                        <tbody class="payments-list">
                            {% for payment in payments %}
                                <tr class="payment-item">
                                    <td>
                                        {% with user=payment.user %}
                                            {{ user.first_name }} {{ user.last_name }}
                                        {% endwith %}
                                    </td>
                                    <td>{{ payment.date }}</td>
                                    <td>{{ payment.amount }}</td>
                                    <td>
                                        {% if payment.document %}
                                            <div class="document-preview">
                                                <a href="{{ payment.document.url }}" class="btn btn-warning" target="_blank" title= '{% trans "Document Preview" %}'>
                                                    {% trans "View" %}
                                                </a>
                                                <div class="tooltip">
                                                    <img src="{{ payment.document.url }}" alt='{% trans "Document Preview" %}' style="width: 100px;">
                                                </div>
                                            </div>
                                        {% else %}
                                            {% trans "No Document" %}
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card mb-4">
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>{% trans "Total Amount" %}</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>{{ folder.parent1.first_name }} {{ folder.parent1.last_name }} : {{ parent1_total }} €</td>
                            </tr>
                            <tr>
                                <td>{{ folder.parent2.first_name }} {{ folder.parent2.last_name }} : {{ parent2_total }} €</td>
                            </tr>
                            <tr>
                                <td>{{ difference }} € {% trans "In Favor Of" %}  {{ in_favor_of.first_name }} {{ in_favor_of.last_name }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Payments/templates/Payments/submit_payment_document_lawyer.html
<!-- add_payment_document.html -->
{% extends 'fExtra/base.html' %}
{% load static i18n crispy_forms_tags %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-sm">
                <div class="card-header bg-primary text-white">
                    <h3 class="text-center mb-0">{% trans "Add Payment Document" %}</h3>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        {{ form.parent|as_crispy_field }}
                        {{ form.amount|as_crispy_field }}
                        <div class="form-group">
                            <label for="{{ form.category.id_for_label }}">{{ form.category.label }}</label>
                            <select class="form-control" id="{{ form.category.id_for_label }}" name="{{ form.category.name }}">
                                <option value="">{% trans "Select a category" %}</option>
                                {% for category_type, categories in grouped_categories.items %}
                                    <optgroup label="{{ category_type }}">
                                        {% for category in categories %}
                                            <option value="{{ category.pk }}" {% if category.pk == form.category.value %}selected{% endif %}>{{ category.name }}</option>
                                        {% endfor %}
                                    </optgroup>
                                {% endfor %}
                            </select>
                            <!-- Button to open modal to add a new category -->
                            <button type="button" class="btn btn-secondary btn-sm mt-2" data-toggle="modal" data-target="#addCategoryModal">
                                {% trans "Add New Category" %}
                            </button>
                        </div>
                        {{ form.date|as_crispy_field }}
                        {{ form.document|as_crispy_field }}
                        <button type="submit" class="btn btn-primary btn-block mt-3">{% trans "Submit" %}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal for adding new category -->
<div class="modal fade" id="addCategoryModal" tabindex="-1" role="dialog" aria-labelledby="addCategoryModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addCategoryModalLabel">{% trans "Add New Category" %}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="addCategoryForm">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="new_category_name">{% trans "Category Name" %}</label>
                        <input type="text" class="form-control" id="new_category_name" name="new_category_name" required>
                    </div>
                    <div class="form-group">
                        <label for="new_category_description">{% trans "Description" %}</label>
                        <textarea class="form-control" id="new_category_description" name="new_category_description"></textarea>
                    </div>
                    <button type="button" class="btn btn-primary mt-2" id="saveCategoryButton">{% trans "Save" %}</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
<script>
    $(document).ready(function() {
        $('#saveCategoryButton').on('click', function() {
            var newCategoryName = $('#new_category_name').val();
            var newCategoryDescription = $('#new_category_description').val();
            var csrfToken = $('[name="csrfmiddlewaretoken"]').val();

            $.ajax({
                url: "{% url 'Payments:add_category' %}",
                type: "POST",
                data: {
                    'new_category_name': newCategoryName,
                    'new_category_description': newCategoryDescription,
                    'csrfmiddlewaretoken': csrfToken
                },
                success: function(response) {
                    if (response.success) {
                        var newOption = $('<option></option>')
                            .attr('value', response.category_id)
                            .text(response.category_name)
                            .prop('selected', true);
                        $('#{{ form.category.id_for_label }}').append(newOption);
                        $('#addCategoryModal').modal('hide');
                    } else {
                        alert(response.error);
                    }
                },
                error: function() {
                    alert("{% trans 'An error occurred. Please try again.' %}");
                }
            });
        });
    });
</script>
{% endblock %}